//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 04:56:48 PM CDT 
//


package org.abs.webservices;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.abs.webservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.abs.webservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStories }
     * 
     */
    public GetStories createGetStories() {
        return new GetStories();
    }

    /**
     * Create an instance of {@link StoriesResponse }
     * 
     */
    public StoriesResponse createStoriesResponse() {
        return new StoriesResponse();
    }

    /**
     * Create an instance of {@link Story }
     * 
     */
    public Story createStory() {
        return new Story();
    }

}
