//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 04:56:48 PM CDT 
//


package org.abs.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Story" type="{abs.org/webservices}Story"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "story"
})
@XmlRootElement(name = "storiesResponse")
public class StoriesResponse {

    @XmlElement(name = "Story", required = true)
    protected Story story;

    /**
     * Gets the value of the story property.
     * 
     * @return
     *     possible object is
     *     {@link Story }
     *     
     */
    public Story getStory() {
        return story;
    }

    /**
     * Sets the value of the story property.
     * 
     * @param value
     *     allowed object is
     *     {@link Story }
     *     
     */
    public void setStory(Story value) {
        this.story = value;
    }

}
